name: manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word

jobs:
  run:
    runs_on: ubuntu-latest
    steps:
      - run: echo "${{inputs.greeting}}"